### ISSUE TITLE
./node_modules/.bin/commit-msg need file to run pre-commit

### ISSUE THREAD

**Issue by premiumwd** [observing/pre-commit#110]
after successful pre-commit got error after scripts ran and finished.
`.git/hooks/commit-msg: line 9: ./node_modules/.bin/commit-msg: No such file or directory`

**Comment by premiumwd** [comment]
can someone just paste that file here from their project?

**Comment by premiumwd** [comment]
fuck you

**Comment by kevinsalter** [comment]
I'm also experiencing this, what the fix? cheers

**Comment by premiumwd** [comment]
decided to use husky, better.
