### ISSUE TITLE
invoking npm with cp.spawn doesn't work on windows

### ISSUE THREAD

**Issue by ForbesLindesay** [observing/pre-commit#14]
This fails on windows with the error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

because you can't use `spawn` to invoke npm on windows.

**Comment by noyobo** [comment]
[pre-commit](https://www.npmjs.com/package/pre-commit) version is 0.0.9 published 7 months ago
This doesn't work on Windows,
Can publish a new version ?

**Comment by 3rd-Eden** [comment]
@noyobo Publishing right away.

**Comment by 3rd-Eden** [comment]
I'm going to close this as I assume that current master fixes all the things.

**Comment by noyobo** [comment]
:+1:  Thank you
