### ISSUE TITLE
Ignore version number bump commits

### ISSUE THREAD

**Issue by blakeembrey** [observing/pre-commit#17]
For example, when running `npm version patch` or doing a bower version update which makes a commit and tag.

**Comment by 3rd-Eden** [comment]
Why would you want to ignore those commits? I would say it's especially important to run the hooks at that moment to ensure that you're not releasing a broken build?

**Comment by blakeembrey** [comment]
Fair enough. It was just a thought based on the duration some tests take and the fact that this commit shouldn't be changing anything that needs testing.

**Comment by 3rd-Eden** [comment]
You can always skip these commits using the `-n` flag.

**Comment by 3rd-Eden** [comment]
I see that npm also included support for git signing, so they might also be willing to add support for hook skipping: https://github.com/npm/npm/blob/master/lib/version.js#L148-L162

I think it would make more sense to solve this in npm & bower instead of this pre-commit module.

**Comment by blakeembrey** [comment]
Perfect, thank you! :smile:
