### ISSUE TITLE
Support other git hooks

### ISSUE THREAD

**Issue by danvk** [observing/pre-commit#25]
e.g. `pre-push`. It seems silly to have separate projects (e.g. https://www.npmjs.com/package/prepush-hook) for each different hook.

**Comment by longlho** [comment]
:+1: for this. Happy to submit a PR of the owner is cool w/ it.

**Comment by 3rd-Eden** [comment]
Well, it would be kinda weird to have as the suggested functionality doesn't match the name of the module. But I having tons of separate modules is silly as well. I guess we could install the various of hooks based on the contents of the `package.json`. Thoughts on this @Swaagie ?

**Comment by Swaagie** [comment]
Could also push the same project to two different names, e.g. one to pre-commit and one to pre-push and have a prepublish script here that `sed` an env variable in https://github.com/observing/pre-commit/blob/master/hook, or is that wack ;)

**Comment by danvk** [comment]
That's wack :)

I wouldn't find it jarring for a project named `pre-commit` to support other git hooks. In fact, I was surprised that it didn't (hence this issue).

If the name is bothersome, though, I'd suggest renaming this package to `git-hooks` or some such, and [deprecating the old name][1].

[1]: http://stackoverflow.com/a/28841779/388951

**Comment by brycefisher** [comment]
Ditto on that last suggestion. I was just about to open this issue myself.

I prefer the `git-hooks` name over `pre-commit` if the plan is to support multiple modules. Otherwise, it's :fork_and_knife: time ;-)

**Comment by danvk** [comment]
Unfortunately another npm package already took the name git-hooks

**Comment by operatino** [comment]
So have you decided on something, which module is recommended for setting up pre-push hooks?

**Comment by jpodwys** [comment]
Also curious whether a conclusion has been reached.

**Comment by 3rd-Eden** [comment]
@jpodwys I'm fine with supporting addition hooks, but with some addition constraints that do not apply to the "core" hook of this project, the pre-commit hook. 

- If non-default hooks exists they should *not* be overrided by default with githook.
- The new git hooks do not execute by default, pre-commit would be the only hook that executes `npm test` by default if no `pre-commit` key is found in the `package.json` these new hooks require opt-in by adding `pre-push` keys to the package.json in order for them to run.

This eliminates any accidental hook overrides for existing users and prevents multiple `npm test` executions. As for the progress on this work, i'm accepting contributions here as my own personal schedule is quite full (read overflowing with work ;p) atm so it would take some while before I can find some time to add this all in.

**Comment by fatso83** [comment]
Why try to cram all of this into this one module anyway? I'd rather see a kind of `githooks-core` package that supported all the common plumbing, and then let that be used by various modules for custom behaviour. Having all the historic baggage of this package affect other hooks seems silly. This package could then depend on `core`.

**Comment by mpareja** [comment]
:+1: to what @fatso83 said.

**Comment by sandy-adi** [comment]
The [pre-push](https://www.npmjs.com/package/pre-push) hook is an exact copy of this repo except for a find and replace of `commit` with `push`. It might not be necessary to have different modules for this as of now. Cause essentially you would just be adding a config to enable push hooks.

**Comment by bumbu** [comment]
[typicode/husky](https://github.com/typicode/husky) seems to do that

**Comment by vinogradov** [comment]
Oh really thank you @bumbu for the link. It solves the problem.

**Comment by QuantumInformation** [comment]
any update on pre-push added to this?

**Comment by fatso83** [comment]
@QuantumInformation Just use a package dedicated to the problem, such as `husky` mentioned above.

**Comment by QuantumInformation** [comment]
already switched to husky thx
