### ISSUE TITLE
sourcing .bash_profile clash with nvm

### ISSUE THREAD

**Issue by mcollina** [observing/pre-commit#33]
If you are developing using [nvm](https://github.com/creationix/nvm), sourcing the bash profile will change which node version are you targeting. This means that if you are developing a native addon against iojs and your default is 0.10, everything falls apart.

A quick solution for this might be checking if node is already present, and if so do not source. I will send a PR with this fix.

Side note, can you please bump the MINOR or at least the MAJOR when you change the hook? It broke a lot of stuff for the way I work.

**Comment by 3rd-Eden** [comment]
@mcollina I never expected that such small change would break things. So I did patch bump as it actually fixed broken installations of pre-commit. So semver wise, it made sense to do a patch release. And yes, checking for Node before sourcing might be a better approach here.

**Comment by mcollina** [comment]
Yes, I agree! It's more a suggestion: given how critical that script is,
it's probably worth a minor bump every time is touched, just in case.

If some people have an issue with the current version, they can always
upgrade. In this way, nobody gets hurt.
Il giorno mer 10 giu 2015 alle 14:44 Arnout Kazemier <
notifications@github.com> ha scritto:
