### ISSUE TITLE
Windows fails to run hook bash script

### ISSUE THREAD

**Issue by killanaca** [observing/pre-commit#42]
Hi
when i try to install the new version v1.1.0, it fails on row 26 of install.js
if (shelly.exec(hook +' --dry-run', { silent: true }).code !== 0) {..}

If i change silent to false and run node install.js from pre-commit folder, it gives me
"...\node_modules\pre-commit\hook" non è riconosciuto come comando interno o esterno,  un programma eseguibile o un file batch.
pre-commit:
pre-commit: The --dry-run of the pre-commit hook failed to execute.
pre-commit:
pre-commit: The hook was not installed.
pre-commit:

because windows cant run 
> ./hook --dry-run

Instead i must use
> sh ./hook --dry-run 

sh.exe is the emulator on windows of unix shell installed with msysgit (git for windows) for example

**Comment by 3rd-Eden** [comment]
Already on it - I noticed this as well. I hope to have a solution in a hour or so. If not, i'll rollback the `--dry-run` check and release that as 1.1.1

**Comment by 3rd-Eden** [comment]
Released a 1.1.1 with the removal.
