### ISSUE TITLE
.git/hooks/pre-commit is not +x on Unix systems

### ISSUE THREAD

**Issue by mcollina** [observing/pre-commit#88]
https://github.com/observing/pre-commit/commit/a9c973224a299a03aef66b5fd1a3b5d566edfee6#diff-f16acefe4b6553580c43edab685f50f3 creates a file that does not have `+x` set on Unix systems, making it *not executable*.

**Comment by elclanrs** [comment]
Same here, I need to run `chmod a+x .git/hooks/pre-commit`...

**Comment by mcollina** [comment]
Thanks so much @3rd-Eden!!!!!

**Comment by dwightjack** [comment]
Hi,

having the same issue with v1.2.1.

I'm on a Mac with node v6.9.1 (nvm) and npm v3.10.9.
The hook file is created with `-r----x--t`. Any hint on how to solve it?

Thanks!

**Comment by josegal** [comment]
Hi -- I the fix wasn't quite right -- that -r----x--t happens when 777 is interpreted as decimal instead of octal.  I have just pushed https://github.com/observing/pre-commit/pull/90 to fix this

**Comment by dwightjack** [comment]
Thanks! :)

**Comment by 3rd-Eden** [comment]
Published 1.2.2 with #90 hopefully that will unfuck my fuckups.

**Comment by dwightjack** [comment]
I tested it and now works flawlessly.

Thank you!
