### ISSUE TITLE
Nothing happens after ng test is successfully run

### ISSUE THREAD

**Issue by jbprat** [observing/pre-commit#95]
Hello, I am trying to make run your precommit hook on this environment:
 - angular 2.3.1
 - jasmine-core 3.3.1
 - karma-jasmine 1.0.2
 - karma 1.2.0
 - pre-commit 1.2.2
 - W10

When I run git commit the test pass successfully but then nothing happens.

**Comment by jbprat** [comment]
This wasn't a pre-commit problem, it came from the fact that ng test watch the files by default. 
I needed to add this script to my package.json :    ` "test-once": "ng test --watch=false",`

**Comment by 3rd-Eden** [comment]
Thanks for the update <3
